// Generated by scripts/generate-editor-typings.mjs (run by build:preset / postinstall)
import { editorTypingsSource } from '@/lib/tampermonkey-editor-typings.generated'

/**
 * Load Tampermonkey type definitions (preset editor-typings.d.ts).
 * Content is generated from preset/src/editor-typings.d.ts by build:preset / generate:editor-typings.
 * @returns Type definitions as a string
 */
export function loadTampermonkeyTypings(): string {
  return editorTypingsSource
}
