/** Public path to the Chrome extension ZIP (generated by `pnpm pack:extension`). */
export const CHROME_EXTENSION_ZIP_PATH = '/downloads/magickmonkey-chrome-extension.zip'

/** Suggested filename when saving the extension ZIP in the browser. */
export const CHROME_EXTENSION_ZIP_FILENAME = 'magickmonkey-chrome-extension.zip'
